# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the aw36429 i2c driver.
#

obj-$(CONFIG_FLASHLIGHT_AW36429)	+= flashlights-aw36429.o

#i2c-core-objs 			:= i2c-core-base.o i2c-core-smbus.o

#ccflags-$(CONFIG_I2C_DEBUG_CORE) := -DDEBUG
