# SPDX-License-Identifier: GPL-2.0-only
#
ccflags-y += -I$(srctree)/techpack/camera/include/uapi
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_utils
ccflags-y += -I$(srctree)


obj-$(CONFIG_SPECTRA_CAMERA) += pico_camera_sysfs_utils.o
